/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TodoItemDto { 
    id?: number;
    listId?: number;
    title?: string | null;
    done?: boolean;
    priority?: number;
    note?: string | null;
}

