/**
 * Todo API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TodoItemDto } from './todoItemDto';


export interface TodoListDto { 
    id?: number;
    title?: string | null;
    colour?: string | null;
    items?: Array<TodoItemDto> | null;
}

